dist: trusty
sudo: false

language: node_js
node_js:
  - "lts/*"
  - "node"

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install

# We are running browser tests
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test:ci

after_success:
  - codecov < coverage/*/lcov.info
