import { createActions } from 'redux-actions';

export default createActions(
  'CHANGE_RESERVATION_SEARCH_FILTERS',
  'CHANGE_RESOURCE_SEARCH_FILTERS',
  'CLEAR_RESOURCE_SELECTOR',
  'HIDE_RESERVATION_CANCEL_MODAL',
  'HIDE_RESERVATION_INFO_MODAL',
  'HIDE_RESOURCE_INFO_MODAL',
  'HIDE_RESOURCE_IMAGES_MODAL',
  'HIDE_RESOURCE_SELECTOR_MODAL',
  'SAVE_CATERING_DATA',
  'SHOW_RESERVATION_CANCEL_MODAL',
  'SHOW_RESERVATION_INFO_MODAL',
  'SHOW_RESOURCE_INFO_MODAL',
  'SHOW_RESOURCE_IMAGES_MODAL',
  'SHOW_RESOURCE_SELECTOR_MODAL',
);
