export default {
  RESOURCE_FAVORITE_POST_ERROR: 'RESOURCE_FAVORITE_POST_ERROR',
  RESOURCE_FAVORITE_POST_REQUEST: 'RESOURCE_FAVORITE_POST_REQUEST',
  RESOURCE_FAVORITE_POST_SUCCESS: 'RESOURCE_FAVORITE_POST_SUCCESS',

  RESOURCE_UNFAVORITE_POST_ERROR: 'RESOURCE_UNFAVORITE_POST_ERROR',
  RESOURCE_UNFAVORITE_POST_REQUEST: 'RESOURCE_UNFAVORITE_POST_REQUEST',
  RESOURCE_UNFAVORITE_POST_SUCCESS: 'RESOURCE_UNFAVORITE_POST_SUCCESS',

  RESOURCE_GET_ERROR: 'RESOURCE_GET_ERROR',
  RESOURCE_GET_REQUEST: 'RESOURCE_GET_REQUEST',
  RESOURCE_GET_SUCCESS: 'RESOURCE_GET_SUCCESS',

  RESOURCES_GET_ERROR: 'RESOURCES_GET_ERROR',
  RESOURCES_GET_REQUEST: 'RESOURCES_GET_REQUEST',
  RESOURCES_GET_SUCCESS: 'RESOURCES_GET_SUCCESS',
};
