export default {
  RESERVATION_POST_ERROR: 'RESERVATION_POST_ERROR',
  RESERVATION_POST_REQUEST: 'RESERVATION_POST_REQUEST',
  RESERVATION_POST_SUCCESS: 'RESERVATION_POST_SUCCESS',

  RESERVATIONS_GET_ERROR: 'RESERVATIONS_GET_ERROR',
  RESERVATIONS_GET_REQUEST: 'RESERVATIONS_GET_REQUEST',
  RESERVATIONS_GET_SUCCESS: 'RESERVATIONS_GET_SUCCESS',

  RESOURCE_FAVORITE_POST_ERROR: 'RESOURCE_FAVORITE_POST_ERROR',
  RESOURCE_FAVORITE_POST_REQUEST: 'RESOURCE_FAVORITE_POST_REQUEST',
  RESOURCE_FAVORITE_POST_SUCCESS: 'RESOURCE_FAVORITE_POST_SUCCESS',

  RESOURCE_UNFAVORITE_POST_ERROR: 'RESOURCE_UNFAVORITE_POST_ERROR',
  RESOURCE_UNFAVORITE_POST_REQUEST: 'RESOURCE_UNFAVORITE_POST_REQUEST',
  RESOURCE_UNFAVORITE_POST_SUCCESS: 'RESOURCE_UNFAVORITE_POST_SUCCESS',

  RESOURCE_GET_ERROR: 'RESOURCE_GET_ERROR',
  RESOURCE_GET_REQUEST: 'RESOURCE_GET_REQUEST',
  RESOURCE_GET_SUCCESS: 'RESOURCE_GET_SUCCESS',

  RESOURCES_GET_ERROR: 'RESOURCES_GET_ERROR',
  RESOURCES_GET_REQUEST: 'RESOURCES_GET_REQUEST',
  RESOURCES_GET_SUCCESS: 'RESOURCES_GET_SUCCESS',

  UNITS_GET_ERROR: 'UNITS_GET_ERROR',
  UNITS_GET_REQUEST: 'UNITS_GET_REQUEST',
  UNITS_GET_SUCCESS: 'UNITS_GET_SUCCESS',
};
